/*
 * Copyright (c) 2019 Davide Avagliano
 */

package it.giovanni.next.rubrica.db

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "contacts")
data class Contact(

    // our primary key, autogenerated
    @PrimaryKey(autoGenerate = true) var id: Int,

    // the first name
    @ColumnInfo(name = "first") var first: String,

    // the last name
    @ColumnInfo(name = "last") var last: String,

    // the phone number
    @ColumnInfo(name = "phone") var phone: String
)